### ISSUE TITLE
Is it possible to use the library with vite in a browser?

### ISSUE THREAD

**Issue by catalin-bratu** [mswjs/source#48]
## Description

I'm trying to use the library in a vue vite application, however process.env and process.cwd are undefined in dev mode.

Is the library solely for usage with Node.js?

It looks quite promising in compassion to your competitors.

**Comment by kettanaito** [comment]
Hi, @catalin-bratu. 

Yes, you can use `@mswjs/source` in the browser. The code it ships is neutral and doesn't rely on the Node.js API. 

> however process.env and process.cwd are undefined in dev mode.

These are likely coming from your code. There's no dependency on `process` in Source.

**Comment by catalin-bratu** [comment]
I will try to set up a sandbox to see if I can reproduce the issue in a fresh install of vite.

**Comment by catalin-bratu** [comment]
Maybe, I wasn't very clear. I tried to use this in the browser.

 import { fromOpenApi } from '@mswjs/source/open-api'
import spec from './api.spec.json'
 
const handlers = await fromOpenApi(spec)

**Comment by syhner** [comment]
@catalin-bratu there's an upstream dependency `@mswjs/source` -> `@apidevtools/swagger-parser` -> `@apidevtools/json-schema-ref-parser`

which is probably the source of your error
see https://github.com/APIDevTools/json-schema-ref-parser/issues/354#issuecomment-2263894801 for solution

@kettanaito if you want to add a short sentence about browser support somewhere in the docs

**Comment by yayobyte** [comment]
I solved it this way:

install this library: https://www.npmjs.com/package/vite-plugin-node-polyfills

```
//vite.config.ts
import { nodePolyfills } from 'vite-plugin-node-polyfills'

export default defineConfig({
  plugins: [
    react(),
    //add this plugin to the plugins array
    nodePolyfills({
      include: ['path'],  // To add only specific polyfills, for this bug you only need path
    }),
  ],
})

```

Then it worked perfectly for me using VITE
