### ISSUE TITLE
OpenAPI: Browser support without polyfills

### ISSUE THREAD

**Issue by tjosepo** [mswjs/source#49]
## Description

The function `fromOpenApi` currently doesn't work on the browser without a lot of Node.js polyfills.

- The file [open-api-utils.ts](https://github.com/mswjs/source/blob/main/src/open-api/utils/open-api-utils.ts) uses status codes from `node:http`.
- The transitive dependency @apidevtools/swagger-parser > [@apidevtools/json-schema-ref-parser](https://github.dev/APIDevTools/json-schema-ref-parser) uses the `path`, `fs`, `http` and `https` modules. It also references `process.cwd`.

## Solution

For [open-api-utils.ts](https://github.com/mswjs/source/blob/main/src/open-api/utils/open-api-utils.ts), inlining the `STATUS_CODE` variable is easy enough.

For [@apidevtools/json-schema-ref-parser](https://github.dev/APIDevTools/json-schema-ref-parser), since it is the ubiquitous library used for JSON Schema dereferencing in Node, it may not make sense to replace it in Node. We could create a separate package entrypoint for the browser that prebundles the Node.js modules or replaces the library with web-compatible alternative (that may not support all features of JSON Schema dereferencing, but works for the web.)

## Alternatives

- Ask consumers of the library to bring their own polyfills. Will hurt the ability of teams to adopt this library. (I haven't been able to fully polyfill everything with Webpack, so I don't even know if it's possible.)
- Make @mswjs/source/open-api a Node.js only feature.
- Raise this issue to the `@apidevtools` folks. Make the change there.

**Comment by weyert** [comment]
Yeah, I think that's a good idea. I am wondering if we could leverage a package like [@stoplight/http-spec](https://www.npmjs.com/package/@stoplight/http-spec). They also have a fork of [@apidevtools/json-schema-ref-parser](https://github.dev/APIDevTools/json-schema-ref-parser) which appears to work in the browser but I am not sure if they use poly fills for it (probably?).

**Comment by kettanaito** [comment]
Thanks for opening this, @tjosepo. I would love to see Source working in the browser for OpenAPI. Our best approach here is to find packages that can provide us with parsing while not relying on Node.js native modules.  

@weyert, `http-spec` looks interesting. Do you have some usage examples of how it parses the OAS documents? I'd love to see those.

**Comment by VobileLiuZhiwu** [comment]
@kettanaito @tjosepo @weyert I believe a better solution would be to provide an initialization command that generates the JSON string for the `specification` needed by `const specification = await SwaggerParser.dereference(document)`, which can then be passed as an argument to `fromOpenApi`. What do you think?

**Comment by tjosepo** [comment]
@VobileLiuZhiwu OpenAPI specifications can have circular references, but JSON strings do not support circular references. Because of this, I don't think this approach is suitable. I still think dereferencing at runtime with a custom implementation is best.

**Comment by kettanaito** [comment]
## Released: v0.3.0 🎉

This has been released in v0.3.0!

- 📄 [**Release notes**](https://github.com/mswjs/source/releases/tag/v0.3.0)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/source/v/0.3.0)

Make sure to always update to the latest version (`npm i @mswjs/source@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
