### ISSUE TITLE
@yellow-ticket/seed-json-schema should use "example" if it is provided

### ISSUE THREAD

**Issue by vchirikov** [mswjs/source#50]
Hi, I found that `@yellow-ticket/seed-json-schema` only uses `examples` property of schema, but some of frameworks generate `example` property, 

```js
"commit": {
  "type": "string",
  "description": "Full git commit hash",
  "example": "80a3fb1345c65f324bb4d56e09b240ac183d9446"
}
```

It will be nice to have a check for the `example` property too.

**Comment by kettanaito** [comment]
Hi, @vchirikov. Thanks for raising this!

I made the repo for https://github.com/yellow-ticket/seed-json-schema public so we can discuss this issue there.
