### ISSUE TITLE
Support ts-rest

### ISSUE THREAD

**Issue by spence-novata** [mswjs/source#56]
## Description

Generate handlers out of a ts-rest contract

```
import { fromTsRest } from '@mswjs/source/ts-rest'

fromTsRest(input)
```

I'm not sure if this issue should be on the Source repo or the ts-rest one. I'm taking the lead of the one for trpc.

**Comment by kettanaito** [comment]
Hi, @spence-novata. That's a good suggestion! But it belongs in a community package. As I mention in the [docs](https://source.mswjs.io/docs/faq#can-i-generate-request-handlers-from-xyz), Source isn't designed to include all the integrations for possible API libraries. I want to encourage people creating their own packages and publishing those. Let me know if Source can expose something to make community packages easier.
