### ISSUE TITLE
`fromOpenApi` mishandling `Accept` header

### ISSUE THREAD

**Issue by Kiskae** [mswjs/source#61]
## Description

The accept header can contain whitespace in addition to ',' between content types, if the content schema does not match the first content type then it doesn't match at all.

## Reproduction steps

- Make an openAPI content handler for `*/*`
- Send a request with an accept header with multiple content types: `Accept: text/html, */*`
- Observe that while it responds, the response won't have a body.

## Expected behavior

The content returns as described by the openapi spec.

## Initial assessment

In https://github.com/mswjs/source/blob/main/src/open-api/utils/open-api-utils.ts `toHeaders` and `toBody` split the accept header using `.split(',')`. This means that all content-types besides the first are prefixed by existing whitespace in the accept header.
This then gets included in the regex, which makes it fail to match since the openapi content types usually don't contain whitespace.

Currently I'm patching this by adding `.trim()` to the `contentTypeToRegExp` method.

**Comment by kettanaito** [comment]
Hi, @Kiskae. Thanks for reporting this.

Would I be correct to assume that this can be fixed by ading `.map(x => x.trim())` in here?

https://github.com/mswjs/source/blob/adaa00fd06bc0d67e9aa19790494c283f982e9a8/src/open-api/utils/open-api-utils.ts#L85-L87

If so, would you be interested in opening a pull request to help us fix this?

**Comment by kettanaito** [comment]
## Released: v0.3.1 🎉

This has been released in v0.3.1!

- 📄 [**Release notes**](https://github.com/mswjs/source/releases/tag/v0.3.1)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/source/v/0.3.1)

Make sure to always update to the latest version (`npm i @mswjs/source@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
