### ISSUE TITLE
Generated HAR handlers cannot respond to the same URL more than once

### ISSUE THREAD

**Issue by danielegarciav** [mswjs/source#66]
## Description

When using `fromTraffic()` with HAR responses, if the app makes a request to the same URL more than once, and that request gets handled by the same generated handler more than once, MSW's request handling logic will throw, and the app will not receive any response moving forward.

## Reproduction steps

1. Create a HAR with a single request+response on some URL.
2. Set up MSW with `fromTraffic` using this HAR.
3. Fetch the URL twice (with the same HTTP method), and try to read the contents of the response each time. On the second attempt, the app will fail to read the response.

## Expected behavior

Each HAR entry should return a usable response no matter how many times the same URL is requested.

## Initial assessment

https://github.com/mswjs/source/blob/9728e372cf8f430e307506bf6c04bed06b5ab3d2/src/traffic/from-traffic.ts#L50-L73

For each HAR entry, the response is created once in line 50. The generated handler for the HAR entry then returns that response instance directly in line 72. Subsequent requests handled by this handler will then return the same response instance, even if it has already been consumed.

Patching line 72 to:

```js
     return response.clone()
```

seems to resolve the issue, by ensuring the returned response instances are always unconsumed. We could edit this function to clone the response if `once` is not true.

**Comment by kettanaito** [comment]
Hi, @danielegarciav. Thanks for reporting this.

This looks like a bug in Source. We can fix it by moving this line to be in the handler's closure:

https://github.com/mswjs/source/blob/9728e372cf8f430e307506bf6c04bed06b5ab3d2/src/traffic/from-traffic.ts#L50

That way, a new response is created from the HAR each time the handler is hit. 

I'm not sure what is faster: clone the same response instance or create it anew. We'd be paying overhead on cloning it on the first request, where no clone is technically necessary. We'd be paying even bigger overhead by adding the logic that keeps track if this handler has been called before. 

I vote for creating the response within the handler. 

Would you like to open a pull request with this change?

**Comment by danielegarciav** [comment]
Thanks for looking at this @kettanaito. According to the MDN docs, `Response.clone()` works like `ReadableStream.tee()` on the underlying `response.body` - it doesn't duplicate the entire source content right away, instead, it works as follows:

- Response A is cloned using `response.clone()`, and now we have Response B, both are internally linked to the same data source.
- If `x` amount of bytes out of Response A are read, that `x` amount bytes is stored in memory until `x` amount of bytes are read from Response B too. The same happens if we swap A and B.
- If the entire Response A is read and Response B is not read at all, then the entire source content is buffered in memory until both responses are fully read.
- If we clone the unread response into a Response C, D, E and so on, they are all still linked to the same internal buffer, and so no extra memory is allocated for the source content.

This library parses out the entire source content to memory the moment we call `toResponse()`. Using `Response.clone()` might actually be beneficial because we'd then only have to parse the response data once, and the parsed data stays in memory ready to be re-used. On the other hand, if we call `toResponse()` each time the handler is hit, we would be decoding the HAR file contents over and over.

For what it's worth, MSW already clones all responses at least twice each time a mocked response is processed: https://github.com/mswjs/msw/blob/9dc2d71199021c62ad8926555c0313d3b1bd6995/src/browser/setupWorker/start/createRequestListener.ts#L53-L59.

For these reasons I recommend taking the `response.clone()` approach, on handlers that are `!once`.

**Comment by kettanaito** [comment]
> On the other hand, if we call toResponse() each time the handler is hit, we would be decoding the HAR file contents over and over.

This is a good argument. 

Go ahead with the cloning then!

**Comment by kettanaito** [comment]
## Released: v0.3.2 🎉

This has been released in v0.3.2!

- 📄 [**Release notes**](https://github.com/mswjs/source/releases/tag/v0.3.2)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/source/v/0.3.2)

Make sure to always update to the latest version (`npm i @mswjs/source@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
