### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by npeham** [mswjs/source#68]
Dear @kettanaito, 

we would like to use source in one of our projects. Unfortunately we are unclear about the license of the project. Could you clarify the license?

Thanks!

Best Nico

**Comment by kettanaito** [comment]
Hi, @npeham. Oh, thanks for pointing out. I forgot to commit an explicit license file. The project is MIT. I will add the file later today.

**Comment by kettanaito** [comment]
## Released: v0.3.2 🎉

This has been released in v0.3.2!

- 📄 [**Release notes**](https://github.com/mswjs/source/releases/tag/v0.3.2)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/source/v/0.3.2)

Make sure to always update to the latest version (`npm i @mswjs/source@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
