### ISSUE TITLE
Add Debugging for the generated api

### ISSUE THREAD

**Issue by ahmad-reza619** [mswjs/source#70]
## Description
Hello, i would like to suggest to be able to see the generated api by mswjs/source so i know what to expect and know what's wrong if thing goes wrong. maybe the api will look something like this
```ts
import recording from './recording.har'
import traffic from "./recording.har"

const handlers = fromTraffic(traffic)

handlers.debug()

export default handlers

```
where it will be outputting an array of object containing details of what are the specified api like
```json
[
    { "url": "example.com/hello", "method": "GET", "queryParams": { ... } },
    { "url": "example.com/test", "method": "POST", "payload": { ... } }
]
```

**Comment by kettanaito** [comment]
Hi, @ahmad-reza619. Thanks for proposing this.

The API you are describing actually already exists! It's not a part of `handlers` but rather the `setupWorker`/`setupServer` functions, and it's called [`.listHanders()`](https://mswjs.io/docs/api/setup-server/list-handlers).

Here's how you use it:

```ts
import recording from './recording.har'
import traffic from "./recording.har"

const handlers = fromTraffic(traffic)

export default handlers
```

```ts
import { setupServer } from 'msw/node'
import handlers from './handlers.js'

export const server = setupServer(...handlers)

// This will console log the list of handlers.
// In this case, those handlers will show you what
// MSW generates out of your network archive.
console.log(server.listHandlers())
```

## Relates resources

- https://mswjs.io/docs/integrations/browser
- https://mswjs.io/docs/integrations/node

**Comment by ahmad-reza619** [comment]
ah okay, thanks for the info
